## Logistic Regression Excercise 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("Datasets/HR_comma_sep.csv")
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [ ]:
data.groupby('left').mean(numeric_only=True)

# So from this we can select columns that effect a person from leaving the company 
# Satisfaction level 
# average_montly_hours	
# promotion_last_5years
# Salary

satisfaction_level  last_evaluation  number_project  \
left                                                        
0               0.666810         0.715473        3.786664   
1               0.440098         0.718113        3.855503   

      average_montly_hours  time_spend_company  Work_accident  \
left                                                            
0               199.060203            3.380032       0.175009   
1               207.419210            3.876505       0.047326   

      promotion_last_5years      high       low    medium  
left                                                       
0                  0.026251  0.101068  0.450123  0.448810  
1                  0.005321  0.022963  0.608233  0.368804

In [9]:
data_dummies = pd.get_dummies(data['salary'])

In [12]:
data_dummies = data_dummies[['high','low','medium']].replace({True: 1, False: 0})
data_dummies

high  low  medium
0         0    1       0
1         0    0       1
2         0    0       1
3         0    1       0
4         0    1       0
...     ...  ...     ...
14994     0    1       0
14995     0    1       0
14996     0    1       0
14997     0    1       0
14998     0    1       0

[14999 rows x 3 columns]

In [13]:
data = pd.concat([data, data_dummies], axis='columns')

In [14]:
data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years Department  salary  high  low  medium  
0                          0      sales     low     0    1       0  
1                          0      sales  medium     0    0       1  
2                          0      sales  medium     0    0       1  
3                          0      sales     low     0    1       0  
4                          0      sales     low     0    1       0  
...                      ...        ...     ...   ...  ...     ...  
14994                      0    support     low     0    1       0  
14995                      0    support     low     0    1       0  
14996                      0    support     low     0    1       0  
14997                      0    support     low     0    1       0  
14998                      0    support     low     0    1       0  

[14999 rows x 13 columns]

In [16]:
data = data.drop(columns= ['salary'])

In [17]:
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   high  low  medium  
0     0    1       0  
1     0    0       1  
2     0    0       1  
3     0    1       0  
4     0    1       0

In [18]:
from sklearn import model_selection

In [43]:
X = data[['satisfaction_level', 'average_montly_hours','promotion_last_5years','high','low','medium']]
Y = data[['left']]

In [44]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, train_size=0.8, test_size= 0.2)

In [45]:
from sklearn import linear_model

In [46]:
logistic_model = linear_model.LogisticRegression()
logistic_model.fit(X, Y)

d:\Users\mdadn\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [47]:
logistic_model.predict(X_test)

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
logistic_model.score(X_test, Y_test) # The model is 77% accurate

0.771

In [49]:
X_test

satisfaction_level  average_montly_hours  promotion_last_5years  high  \
12074                0.11                   277                      0     0   
4380                 0.61                   254                      0     0   
6074                 0.72                   198                      0     0   
10036                0.85                   123                      0     0   
1797                 0.44                   138                      0     0   
...                   ...                   ...                    ...   ...   
9685                 0.56                   185                      0     0   
1893                 0.10                   302                      0     0   
13098                0.84                   266                      0     0   
139                  0.73                   257                      0     0   
9237                 0.64                   114                      0     0   

       low  medium  
12074    0       1  
4380     1       0  
6074     1       0  
10036    1       0  
1797     1       0  
...    ...     ...  
9685     0       1  
1893     0       1  
13098    1       0  
139      1       0  
9237     0       1  

[3000 rows x 6 columns]

In [50]:
logistic_model.predict([[0.70, 200, 0, 0,0,1]])

d:\Users\mdadn\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [51]:
logistic_model.predict_proba([[0.70, 200, 0, 0,0,1]])

d:\Users\mdadn\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[0.86600044, 0.13399956]])